version: 2.1

orbs:
  architect: giantswarm/architect@6.4.0

workflows:
  test:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          registries-data: public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
      - architect/push-to-app-catalog:
          name: push-to-app-catalog
          context: architect
          requires:
            - push-to-registries
          executor: app-build-suite
          chart: registry-sync
          app_catalog: giantswarm-operations-platform-catalog
          app_catalog_test: giantswarm-operations-platform-test-catalog
          persist_chart_archive: true
          filters:
            branches:
              ignore:
                - main
            tags:
              only: /^v.*/
